### ISSUE TITLE
ckeditor.js?3e5d:235 Uncaught TypeError: Cannot set property 'dir' of undefined

### ISSUE THREAD

**Issue by SX729** [ckeditor/ckeditor-docs#125]
My folder structure is like

src --> widget --> text.vue

node_modules -->ckeditor -->...

in‘ text.vue’，html part Needless to say， I  have written js part like that：
<script>
      import 'ckeditor'
      export default { 
        mounted () {
           this.$nextTick(() => {
              CKEDITOR.replace('editor')
          })
        }  
       }
<script>

but show the dir error
where could I set variable CKEDITOR_BASEPATH?  and is it '../../node_modules/ckeditor'?

**Comment by f1ames** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

---

When it comes to properly setting `CKEDITOR_BASEPATH`, check [this StackOverflow thread](https://stackoverflow.com/questions/36064972/installing-ckeditor-with-npm/36083620#36083620) - in short basepath should be set before requring CKEditor, so in your case:

```
window.CKEDITOR_BASEPATH = 'node_modules/ckeditor/'; // Or something similar.
import 'ckeditor'
...
```

**Comment by SX729** [comment]
sorry, I've got the wrong place ，next time I'll pay attention to it！ Thank you for your answer~ but event if I  set before my include the CKEditor code ，it still  have the error，is it not 'node_modules/ckeditor/'？？
Can you add me QQ 595695827，I want  further discussion

**Comment by f1ames** [comment]
@SX729 please use [StackOverflow](https://stackoverflow.com/questions/tagged/ckeditor) as mentioned before to resolve your further doubts or questions.
