### ISSUE TITLE
Make the "Requirements" box less obtrusive

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor-docs#47]
The green Requirements box (that lists what you need to have to see/use a given feature) seems to stand out a bit too much. Can we make its style a bit less noticeable?

**Comment by oleq** [comment]
Changes in https://github.com/ckeditor/ckeditor-docs/commits/t/47.

**Comment by AnnaTomanek** [comment]
The icons are a step forward, great!

The background/box itself looks pretty & elegant, but I'm not too sure if it wasn't supposed to be more obtrusive than it is now... :D

**Comment by Reinmar** [comment]
Yep - the "requirements" icon is positive (green) while something alarming (yellow perhaps) would fit here better. It actually can be the same icon, just yellow :D

**Comment by wwalc** [comment]
Can you paste screenshots so that I was sure we're talking about same thing? :D

Current version:

![image](https://cloud.githubusercontent.com/assets/545175/7394875/a5a0fec2-ee96-11e4-8296-8972eee981a3.png)


Proposed version:

![image](https://cloud.githubusercontent.com/assets/545175/7394866/9502be02-ee96-11e4-9211-3c17b0d21c33.png)

My $0.02:

The proposed icon rather suggest sharing:
https://www.google.com/search?q=share+icon&espv=2&biw=1745&bih=945&source=lnms&tbm=isch&sa=X&ei=MvtAVeGMBonMyAPHzYGACA&ved=0CAYQ_AUoAQ

![image](https://cloud.githubusercontent.com/assets/545175/7394976/53e36646-ee97-11e4-875d-fc61e75b6733.png)


The requirements could still use a checkbox like it used so far but in a bit different way, so that it looked more like something to check fom the list, not like a success message.

![image](https://cloud.githubusercontent.com/assets/545175/7394955/3ea1208e-ee97-11e4-9bed-e41079976e99.png)

![image](https://cloud.githubusercontent.com/assets/545175/7395051/d78509b4-ee97-11e4-843e-e416f72be2df.png)

I don't have any proposal regarding colors though and feel really bad doing a flame and complaining about a single icon and the color of a box :D

**Comment by fredck** [comment]
For me that box sounds more like an "info" or "warning", so neither a checkbox nor the proposed "share" icon look right, IMHO.

**Comment by wwalc** [comment]
Check the requirements images that google returns (pasted above). Imho having two checkboxes where one is checked and one is empty suggests quite well some kind of a checklist.

**Comment by AnnaTomanek** [comment]
Agreed with @wwalc. Having no better idea, this was the same search that I did and it makes sense. It's just that our tick without the checklist is a bit unclear, but I think we can follow the more obvious checklist image direction.

The share/cogwheels that match/are connected image is a bit inappropriate in our context when we sometimes use the box to inform the users that a particular feature simply requires version X.

**Comment by oleq** [comment]
@wwalc Well... Trust me, I Googled it. And I didn't found any inspiration. It's an abstract noun, which has no clear, single-icon representation.

I think we should use a default info box instead anything fancy:

![screen shot 2015-04-30 at 11 35 38](https://cloud.githubusercontent.com/assets/1099479/7410205/0410dd2e-ef2d-11e4-8a98-a2a099d16709.png)

**Comment by Reinmar** [comment]
The info box makes sense too. Information about requirements is just a special kind of info anyway :D

**Comment by AnnaTomanek** [comment]
Well, it WAS a nice idea to have these two separated, this is specific information that is actually quite helpful before you dig into what's inside the article. A normal tip is just any random additional information that we deem special. I would still vote for keeping them separate. Although I can understand @oleq may not be too happy with spending more time on trying to design one icon.

**Comment by Reinmar** [comment]
If we keep using the class "requirements", then we'll be able to change the icon one day :)

**Comment by AnnaTomanek** [comment]
I doubt anyone's gonna touch this issue "one day", after this discussion :) Realistically, it's either now or never. So @oleq, a question to you - are you able & willing to come up with something based on the "checkbox" idea? If not, let's at least switch the tip icon for the new one. And what about the new background/box styling?

**Comment by oleq** [comment]
> are you able & willing to come up with something based on the "checkbox" idea?

I set myself a deadline at 1pm. If I don't have anything worth sharing, I'll go with default tip.

**Comment by oleq** [comment]
![screen shot 2015-04-30 at 13 04 16](https://cloud.githubusercontent.com/assets/1099479/7411549/667e67cc-ef39-11e4-8fc4-c939386ce02d.png)

**Comment by Reinmar** [comment]
Perfecto! I like the connotation with checking the plug :)
